### ISSUE TITLE
Scrum Update June 25

### ISSUE THREAD

**Issue by KianShah** [nikkimoteva/unDecided#26]
Scrum Update Number 3

Team Name: unDecided
Nikki Moteva q7s1b
Robert Mo w9d1b
Kian Shahangyan l1a1b
Harry Xv g3z0b

**Comment by KianShah** [comment]
- **What did you work on this past iteration (2 weeks)?**
Set up Google OAuth and developed the dashboard for the when the user logs in. Also completely restructured much of the code as issues came up. Also developed some backend code to support authorization and other functions.
- **What were any major issues/challenges you ran into?**
Had a lot of problems with Google's OAuth solution. For some reason, I got SameSite attribute mismatch issues every time I tried running the app on chrome. Still haven't figured it out, but works fine on Firefox.
- **What do you plan to work on for this coming iteration (2 weeks)?**
After the group meeting, we decided that I would be helping Harry on developing the backend, and also implementing some global styles. I'll also work on integrating AWS S3 into the web app

**Comment by nikkimoteva** [comment]
- What did you work on this past iteration (2 weeks)?
I worked on the landing page, and adding some visualizations to support why our product is the best. I added graphs and some transitions.

- What were any major issues/challenges you ran into?
I had some problems coming up with how to represent the data from the Ensemble2 paper, since the data values were very close to each other. I also had some problems coming up with how to style to front page to make it more eye catching.

- What do you plan to work on for this coming iteration (3 weeks)?
After the group meeting, we decided that I would be working on finishing up the landing page based on Ian’s feedback, and also help Robert with developing the jobs page and dashboard.

**Comment by aestrr** [comment]
- What did you work on this past iteration (2 weeks)?
learned more about ensemble2, read into the paper in depth for better integration between the project and ensemble2

- What were any major issues/challenges you ran into?
time management and communication with team

- What do you plan to work on for this coming iteration (2 weeks)?
prioritizing on converting existing python jobs related api to javascript, user setting page / setting up database so that the site can save the settings, FAQ static component page

**Comment by robertmzm** [comment]
What did you work on this past iteration (2 weeks)?
I learned the framework and the integration our team decided to merge into. We also decided to drop the existing signup form and use google's entry instead

What were any major issues/challenges you ran into?
I have some time management issues and I really appreciate my teammates' understanding.

What do you plan to work on for this coming iteration (3 weeks)?
I will be working on the dashboard visualization, job display, and probably the profile and setting page.
